version: v0.10.1
formatter: default
rules:
  - header-min-length
  - header-max-length
  - body-max-line-length
  - type-enum
severity:
  default: error
settings:
  header-min-length:
    argument: 10
  header-max-length:
    argument: 72
  body-max-line-length:
    argument: 72
  type-enum:
    argument:
      - build
      - chore
      - ci
      - docs
      - feat
      - fix
      - perf
      - refactor
      - revert
      - style
      - test
      - wip
